<script lang="ts">
	import { getContext } from 'svelte'
	import type { MediaQuery } from 'svelte/reactivity'
	import { scale } from 'svelte/transition'
	import { X, CopySimple, UploadSimple, DownloadSimple, Broom } from 'phosphor-svelte'
	import usePreviewStore from '@/stores/preview.svelte'
	import Button from '@/components/button.svelte'

	const previewStore = usePreviewStore()

	const onDesktop: MediaQuery = getContext('onDesktop')

	const scaleOnMobile = (node: Element) =>
		onDesktop.current ? scale(node, { duration: 0 }) : scale(node)

	let prevOnDesktop = $state(onDesktop.current)
	$effect(() => {
		if (prevOnDesktop && !onDesktop.current) {
			previewStore.closePreview()
		}
		prevOnDesktop = onDesktop.current
	})
</script>

{#if previewStore.showPreview || onDesktop.current}
	<aside transition:scaleOnMobile>
		<menu>
			<li>
				<Button icon title="close preview" onclick={previewStore.closePreview}>
					<X size={20} weight="regular" />
				</Button>
			</li>
			<li>
				<Button icon title="clear config">
					<Broom size={20} weight="regular" />
				</Button>
			</li>
			<li>
				<Button icon title="upload config">
					<UploadSimple size={20} weight="regular" />
				</Button>
			</li>
			<li>
				<Button icon title="download config">
					<DownloadSimple size={20} weight="regular" />
				</Button>
			</li>
			<li>
				<Button icon title="copy config text">
					<CopySimple size={20} weight="regular" />
				</Button>
			</li>
		</menu>
		<textarea readonly>
			# Generated by https://bitcoin-knots-config-generator.netlify.app/ # This config should be
			placed in following path: # $HOME/Library/Application Support/Bitcoin/bitcoin.conf # [relay] #
			Honor RBF opt-out signal. mempoolreplacement=fee,optin # Reject TRUC transactions entirely.
			mempooltruc=reject # [core] # Certain indexes are enabled (currently just basic).
			blockfilterindex=1 # Keep at most <n> unconnectable transactions in memory. maxorphantx=1000
		</textarea>
	</aside>
{/if}

<style lang="postcss">
	aside {
		display: flex;
		flex-direction: column;
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		background-color: var(--color-background);
	}

	menu {
		display: flex;
		align-items: center;
		column-gap: 0.25rem;
		margin: 0;
		padding: 0.5rem 0.75rem;
		border-bottom: 1px solid var(--color-text-dark);
		list-style: none;

		> li:nth-child(2) {
			margin-left: auto;
		}
	}

	textarea {
		flex-grow: 1;
		width: 100%;
		padding: 0.5rem;
		resize: none;
		border: none;
		background-color: var(--color-background);
		color: var(--color-text-medium);

		&:focus {
			outline: none;
		}
	}

	@media (min-width: 1024px) {
		aside {
			position: relative;
			grid-area: preview;
			border: 1px solid var(--color-text-dark);
		}

		menu {
			> li:first-child {
				display: none;
			}
		}
	}
</style>
