<script lang="ts">
	import { innerWidth } from 'svelte/reactivity/window'
	import { scale } from 'svelte/transition'
	import usePreviewStore from '@/stores/preview.svelte'
	import Button from '@/components/button.svelte'
	import { breakpoint } from '@/globals'

	const previewStore = usePreviewStore()

	const alwaysVisible = $derived(
		innerWidth.current !== undefined && innerWidth.current >= breakpoint,
	)

	const maybeScale = (node: Element) => (alwaysVisible ? scale(node, { duration: 0 }) : scale(node))

	let prevInnerWidth = $state(innerWidth.current)
	$effect(() => {
		if (innerWidth.current! >= breakpoint && prevInnerWidth! < breakpoint) {
			previewStore.closePreview()
		}
		prevInnerWidth = innerWidth.current
	})
</script>

{#if previewStore.showPreview || alwaysVisible}
	<aside in:maybeScale>
		<menu>
			<li>
				<Button onclick={previewStore.closePreview}>X</Button>
			</li>
			<li>Copy</li>
		</menu>
		<textarea readonly>
			# Generated by https://bitcoin-knots-config-generator.netlify.app/ # This config should be
			placed in following path: # $HOME/Library/Application Support/Bitcoin/bitcoin.conf # [relay] #
			Honor RBF opt-out signal. mempoolreplacement=fee,optin # Reject TRUC transactions entirely.
			mempooltruc=reject # [core] # Certain indexes are enabled (currently just basic).
			blockfilterindex=1 # Keep at most <n> unconnectable transactions in memory. maxorphantx=1000
		</textarea>
	</aside>
{/if}

<style lang="postcss">
	aside {
		display: flex;
		flex-direction: column;
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		background-color: var(--color-background);
	}

	menu {
		display: flex;
		align-items: center;
		margin: 0;
		padding: 0.5rem 1rem;
		border-bottom: 1px solid var(--color-text-dark);
		list-style: none;

		> li:nth-child(2) {
			margin-left: auto;
		}
	}

	textarea {
		flex-grow: 1;
		width: 100%;
		padding: 0.5rem;
		resize: none;
		border: none;
		background-color: var(--color-background);
		color: var(--color-text-medium);

		&:focus {
			outline: none;
		}
	}

	@media (min-width: 1024px) {
		aside {
			position: relative;
			grid-area: preview;
			border: 1px solid var(--color-text-dark);
		}

		menu {
			> li:first-child {
				display: none;
			}
		}
	}
</style>
