<aside>
	<textarea readonly>
		# Generated by https://bitcoin-knots-config-generator.netlify.app/ # This config should be
		placed in following path: # $HOME/Library/Application Support/Bitcoin/bitcoin.conf # [relay] #
		Honor RBF opt-out signal. mempoolreplacement=fee,optin # Reject TRUC transactions entirely.
		mempooltruc=reject # [core] # Certain indexes are enabled (currently just basic).
		blockfilterindex=1 # Keep at most <n> unconnectable transactions in memory. maxorphantx=1000
	</textarea>
</aside>

<style>
	aside {
		display: none;
	}

	@media (min-width: 1024px) {
		aside {
			display: flex;
			grid-area: preview;
			border: 1px solid var(--color-text-dark, 'green');
		}
		textarea {
			width: 100%;
			padding: 0.5rem;
			resize: none;
			border: none;
			background-color: var(--color-background, 'black');
			color: var(--color-text-medium, 'green');

			&:focus {
				outline: none;
			}
		}
	}
</style>
