export const repoUrl = 'https://github.com/Sun0fABeach/bitcoin-config-editor'
export const breakpoint = 1024

export const sampleConfigText = `# Generated by https://bitcoin-knots-config-generator.netlify.app/

# This config should be placed in following path:
# $HOME/Library/Application Support/Bitcoin/bitcoin.conf

# [relay]
# Honor RBF opt-out signal. mempoolreplacement=fee,optin # Reject TRUC transactions entirely.
mempooltruc=reject

# [core]
# Certain indexes are enabled (currently just basic).
blockfilterindex=1
# Keep at most <n> unconnectable transactions in memory.
maxorphantx=1000
`
