export const repoUrl = 'https://github.com/Sun0fABeach/bitcoin-config-editor'
export const breakpoint = 1024

/* NOTE: keep colors in sync with css vars in global.css! */
export const colors = {
	textMedium: 'hsl(127.13, 100%, 28.04%)',
	textLight: 'hsl(135.29, 100%, 50%)',
	accent1: 'white',
	accent2: 'hsl(60, 55.24, 58.82%)',
	background: 'hsl(327.27, 73.33%, 2.94%)',
	popoverBackground: 'hsl(120, 100%, 11.57%)',
	layoutBorder: 'hsl(120, 100%, 11.57%)', // same as popoverBackground
	elementBorder: 'hsl(127.13, 100%, 28.04%)', // same as textMedium
}

export const sampleConfigText = `# Generated by https://bitcoin-knots-config-generator.netlify.app/

# This config should be placed in following path:
# $HOME/Library/Application Support/Bitcoin/bitcoin.conf

# [relay]
# Reject TRUC transactions entirely.
mempooltruc=reject

# [core]
# Certain indexes are enabled (currently just basic).
blockfilterindex=1
# Keep at most <n> unconnectable transactions in memory.
maxorphantx=1000

# This config should be placed in following path:
# $HOME/Library/Application Support/Bitcoin/bitcoin.conf

# [relay]
# Reject TRUC transactions entirely.
mempooltruc=reject

# [core]
# Certain indexes are enabled (currently just basic).
blockfilterindex=1
# Keep at most <n> unconnectable transactions in memory.
maxorphantx=1000

# This config should be placed in following path:
# $HOME/Library/Application Support/Bitcoin/bitcoin.conf

# [relay]
# Reject TRUC transactions entirely.
mempooltruc=reject

# [core]
# Certain indexes are enabled (currently just basic).
blockfilterindex=1
# Keep at most <n> unconnectable transactions in memory.
maxorphantx=1000

# This config should be placed in following path:
# $HOME/Library/Application Support/Bitcoin/bitcoin.conf

# [relay]
# Reject TRUC transactions entirely.
mempooltruc=reject

# [core]
# Certain indexes are enabled (currently just basic).
blockfilterindex=1
# Keep at most <n> unconnectable transactions in memory.
maxorphantx=1000

# This config should be placed in following path:
# $HOME/Library/Application Support/Bitcoin/bitcoin.conf

# [relay]
# Reject TRUC transactions entirely.
mempooltruc=reject

# [core]
# Certain indexes are enabled (currently just basic).
blockfilterindex=1
# Keep at most <n> unconnectable transactions in memory.
maxorphantx=1000

# This config should be placed in following path:
# $HOME/Library/Application Support/Bitcoin/bitcoin.conf

# [relay]
# Reject TRUC transactions entirely.
mempooltruc=reject
`
